"""add nullable verified_at column for transactions

Revision ID: c51431f60c99
Revises: 54b099620753
Create Date: 2024-08-25 15:16:15.396079

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c51431f60c99"
down_revision: Union[str, None] = "54b099620753"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("verified_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "verified_at")
    # ### end Alembic commands ###
